apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-build
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
    - name: output-dir
      type: string
      description: The directory for the output artifacts
      default: "build_results"
  workspaces:
    - name: output
      description: The workspace where the Git repository will be cloned and build artifacts will be stored
  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        git clone --recursive --shallow-submodules $(params.repository-url) $(workspaces.output.path)
        cd $(workspaces.output.path)
        git checkout $(params.revision)

    - name: build-clickhouse
      image: ubuntu:22.04
      script: |
        set -x
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y ccache python3 ninja-build nasm yasm gawk lsb-release wget software-properties-common gnupg curl
        wget -qO- https://apt.kitware.com/keys/kitware-archive-latest.asc | apt-key add -
        apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main'
        apt-get update
        apt-get install -y cmake
        wget -O - https://apt.llvm.org/llvm.sh | bash
        export CC=clang-18
        export CXX=clang++-18
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . $HOME/.cargo/env
        rustup toolchain install nightly-2024-04-01
        rustup default nightly-2024-04-01
        rustup component add rust-src
        cd $(workspaces.output.path)
        mkdir build
        cmake -S . -B build
        cmake --build build
