apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
  workspaces:
    - name: output
      description: The workspace where the Git repository will be cloned
  steps:
    - name: clone
      image: "alpine/git:v2.30.2"
      script: |
        git clone $(params.repository-url) $(workspaces.output.path) --branch $(params.revision)
      workspaces:
        - name: output
    - name: build
      image: ubuntu:20.04
      script: |
        apt-get update && apt-get install -y cmake g++ make
        cd $(workspaces.output.path)
        mkdir build && cd build
        cmake ..
        make
      workspaces:
        - name: output
