apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
    - name: output-dir
      type: string
      description: The directory for the output artifacts
      default: "build_results"
  workspaces:
    - name: output
      description: The workspace where the Git repository will be cloned and build artifacts will be stored
  steps:
    - name: build
      image: ubuntu:20.04
      script: |
        # Install required packages
        apt-get update
        apt-get install -y git cmake ccache python3 ninja-build nasm yasm gawk lsb-release wget software-properties-common gnupg
        
        # Install LLVM
        wget -O - https://apt.llvm.org/llvm.sh | bash
        
        # Set environment variables for Clang
        export CC=clang-18
        export CXX=clang++-18
        
        # Install and configure Rust
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        source $HOME/.cargo/env
        rustup toolchain install nightly-2024-04-01
        rustup default nightly-2024-04-01
        rustup component add rust-src
        
        # Clone the ClickHouse repository and build
        git clone --recursive --shallow-submodules $(params.repository-url) $(workspaces.output.path)
        cd $(workspaces.output.path)
        mkdir build
        cmake -S . -B build
        cmake --build build
      workspaces:
        - name: output
