apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: clone-build-taskrun
spec:
  taskRef:
    name: clone-build
  params:
    - name: repository-url
      value: "https://github.com/swapnildear/ClickHouse-tekton.git"
    - name: revision
      value: "master"
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: your-pvc-name
  podTemplate:
    containers:
      - name: step-clone-repo
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "16000m"
      - name: step-build-clickhouse
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "16000m"
