apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-clickhouse-pipeline-run
spec:
  pipelineRef:
    name: clone-clickhouse-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: my-pvc  # replace with your PVC
  params:
    - name: repository-url
      value: https://github.com/swapnildear/ClickHouse-tekton.git
    - name: revision
      value: main
