apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
    - name: revision
      type: string
      default: "main"
  workspaces:
    - name: output
  steps:
    - name: clone
      image: "alpine/git:v2.30.2"
      script: |
        git clone $(params.repository-url) $(workspaces.output.path) --branch $(params.revision)
