apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: clickhouse-build-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: clickhouse-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('X-GitHub-Event', 'push')"
      bindings:
        - ref: clickhouse-trigger-binding
      template:
        ref: clickhouse-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "1Gi"
                    cpu: "500m"

