---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-clickhouse
spec:
  params:
    - name: repository
      description: The Git Repository for the Application Source Code. If empty, the Repository url will be found from toolchain
    - name: branch
      description: The Branch for the Application Source Code
      default: "master"
    - name: revision
      description: The Revision for the Application Source Code
      default: ""    
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
    - name: api
      description: the IBM Cloud api endpoint
      default: "https://cloud.ibm.com"      
    - name: app-name
      description: The name of the application passed as environment variable
    - name: fail-on-lint-errors
      description: Force failure of task when vulnerability advisor scan issues are found
      default: "true"
    - name: fail-on-scanned-issues
      description: Force failure of task when vulnerability advisor scan issues are found
      default: "false"
    - name: pipeline-debug
      default: "0"
    - name: pr-url
      description: The Pull Request URL
    - name: apikey
      description: The IBM Cloud API Key
    - name: commit-timestamp
      description: The Commit Timestamp as set by the Trigger Binding based on the Event Listener invoked
    - name: scm-type
      description: The Source Code Management Type as set by the Trigger Binding based on the Event Listener invoked
    - name: project-id
      description: project id
      default: ""
    - name: artifactory
      description: The variable storing artifactory integration with the toolchain
    - name: virtual-server-instance
      description: The IP Address of the Virtual Server Instance
    - name: host-ssh-keys
      description: The private SSH Key required to login to the Virtual Server Instance
    - name: host-user-name
      description: The username required to login to the Virtual Server Instance 
    - name: inventory-repo
      description: The variable storing git integration for the repository storing build inventory with the toolchain
    - name: scripts-repo
      description: The variable storing git integration for the repository storing build code for the toolchain    
    - name: cos-bucket-name
      description: The Cloud Object Storage Bucket name where build artifact will be stored

    - name: insights
      description: The variable storing DevOps Insight integration with the toolchain
    - name: cos-api-key
      description: The API Key to interact with the Cloud Object Storage Instance
    - name: scripts-subpath
      description: The subpath to the script repo from root
    - name: scripts-repo-branch
      description: The branch of the scripts-repo
    - name: inventory-repo-branch
      description: The branch of the inventory-repo
    - name: icr-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: test-app-name
      description: The name of the Test application passed as environment variable
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.icr-dockerconfigjson)
      metadata:
        name: icr-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: clickhouse-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: clickhouse-$(uid)
      spec:
        pipelineRef:
          name: clickhouse-pipeline
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: api
            value: $(params.api)
          - name: region
            value: $(params.region)
          - name: app-name
            value: $(params.app-name)
          - name: fail-on-lint-errors
            value: $(params.fail-on-lint-errors)
          - name: fail-on-scanned-issues
            value: $(params.fail-on-scanned-issues)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: apikey
            value: $(params.apikey)
          - name: pr-url
            value: $(params.pr-url)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id) 
          - name: artifactory
            value: $(params.artifactory)
          - name: virtual-server-instance
            value: $(params.virtual-server-instance)
          - name: host-ssh-keys
            value: $(params.host-ssh-keys)
          - name: host-user-name
            value: $(params.host-user-name)
          - name: region
            value: $(params.region)   
          - name: cos-bucket-name
            value: $(params.cos-bucket-name)
          - name: cos-api-key
            value: $(params.cos-api-key)
          - name: inventory-repo
            value: $(params.inventory-repo)
          - name: scripts-repo
            value: $(params.scripts-repo)                   
          - name: insights
            value: $(params.insights) 
          - name: scripts-subpath
            value: $(params.scripts-subpath)
          - name: scripts-repo-branch
            value: $(params.scripts-repo-branch) 
          - name: inventory-repo-branch
            value: $(params.inventory-repo-branch)
          - name: test-app-name
            value: $(params.test-app-name)                                                
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: clickhouse-$(uid)-pvc
        podTemplate:
          imagePullSecrets:
            - name: icr-pull-secret
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-manual
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: manual-run
spec:
  triggers:
    - binding:
        name: trigger-binding-manual
      template:
        name: trigger-template-clickhouse
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-ent-commit
spec:
  params:
    - name: branch
      value: $(event.ref)
    - name: commit-id
      value: $(event.after)
    - name: commit-timestamp
      value: $(event.repository.pushed_at)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github-ent"
---        
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-ent-commit
spec:
  triggers:
    - bindings: 
        - name: github-ent-commit   
      template:
        name: trigger-template-clickhouse
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-commit
spec:
  params:
    - name: branch
      value: $(event.ref)
    - name: commit-id
      value: $(event.after)
    - name: commit-timestamp
      value: $(event.repository.updated_at)
    - name: repository
      value: $(event.repository.html_url)
    - name: scm-type
      value: "github"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit
spec:
  triggers:
    - bindings:  
        - name: github-commit   
      template:
        name: trigger-template-clickhouse
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: grit-or-gitlab-commit
spec:
  params:
    - name: branch
      value: $(event.ref)
    - name: commit-id
      value: $(event.checkout_sha)
    - name: commit-timestamp
      value: $(event.commits[0].timestamp)
    - name: repository
      value: $(event.project.http_url)
    - name: scm-type
      value: "gitlab"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: grit-or-gitlab-commit
spec:
  triggers:
    - bindings:   
        - name: grit-or-gitlab-commit
      template:
        name: trigger-template-clickhouse
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bitbucket-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.links.html.href)"
    - name: revision
      value: "$(event.push.changes[0].new.target.hash)"
    - name: branch
      value: "$(event.push.changes[0].new.name)"
    - name: commit-timestamp
      value: "$(event.pull_request.head.repo.pushed_at)"
    - name: commit-id
      value: "$(event.pull_request.head.sha)"
    - name: scm-type
      value: "bitbucket"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: bitbucket-commit
spec:
  triggers:
    - binding:
        name: bitbucket-commit
      template:
        name: trigger-template-clickhouse
